### ISSUE TITLE
Cannot find module 'socket.io-client/dist/socket.io.js

### ISSUE THREAD

**Issue by julianoBRL** [heroku-examples/node-socket.io#8]
**Error:** 
```
2020-06-15T22:06:19.317748+00:00 app[web.1]: Error: Cannot find module 'socket.io-client/dist/socket.io.js'
2020-06-15T22:06:19.317748+00:00 app[web.1]: Require stack:
2020-06-15T22:06:19.317749+00:00 app[web.1]: - /app/node_modules/socket.io/lib/index.js
2020-06-15T22:06:19.317749+00:00 app[web.1]: - /app/start_server.js
2020-06-15T22:06:19.317750+00:00 app[web.1]: at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)
2020-06-15T22:06:19.317750+00:00 app[web.1]: at Function.resolve (internal/modules/cjs/helpers.js:78:19)
2020-06-15T22:06:19.317751+00:00 app[web.1]: at resolvePath (/app/node_modules/socket.io/lib/index.js:113:20)
2020-06-15T22:06:19.317751+00:00 app[web.1]: at Server.serveClient (/app/node_modules/socket.io/lib/index.js:116:25)
2020-06-15T22:06:19.317751+00:00 app[web.1]: at new Server (/app/node_modules/socket.io/lib/index.js:53:8)
2020-06-15T22:06:19.317752+00:00 app[web.1]: at Server (/app/node_modules/socket.io/lib/index.js:44:41)
2020-06-15T22:06:19.317752+00:00 app[web.1]: at Object.<anonymous> (/app/start_server.js:10:12)
2020-06-15T22:06:19.317753+00:00 app[web.1]: at Module._compile (internal/modules/cjs/loader.js:1138:30)
2020-06-15T22:06:19.317753+00:00 app[web.1]: at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
2020-06-15T22:06:19.317753+00:00 app[web.1]: at Module.load (internal/modules/cjs/loader.js:986:32) {
2020-06-15T22:06:19.317754+00:00 app[web.1]: code: 'MODULE_NOT_FOUND',
2020-06-15T22:06:19.317754+00:00 app[web.1]: requireStack: [
2020-06-15T22:06:19.317754+00:00 app[web.1]: '/app/node_modules/socket.io/lib/index.js',
2020-06-15T22:06:19.317755+00:00 app[web.1]: '/app/start_server.js'
2020-06-15T22:06:19.317755+00:00 app[web.1]: ]
2020-06-15T22:06:19.317755+00:00 app[web.1]: }
```

**Code:**
```
const express = require('express');
const socketIO = require('socket.io');

const PORT = process.env.PORT || 3000;

const server = express()
  .use((req, res) => res.send("Funciona"))
  .listen(PORT, () => console.log(`Listening on ${PORT}`));

const io = socketIO(server);

io.on('connection', (socket) => {
  console.log('Client connected');
  socket.on('disconnect', () => console.log('Client disconnected'));
});
```
how do I fix this error?

**Comment by julianoBRL** [comment]
> **Error:**
> 
> ```
> 2020-06-15T22:06:19.317748+00:00 app[web.1]: Error: Cannot find module 'socket.io-client/dist/socket.io.js'
> 2020-06-15T22:06:19.317748+00:00 app[web.1]: Require stack:
> 2020-06-15T22:06:19.317749+00:00 app[web.1]: - /app/node_modules/socket.io/lib/index.js
> 2020-06-15T22:06:19.317749+00:00 app[web.1]: - /app/start_server.js
> 2020-06-15T22:06:19.317750+00:00 app[web.1]: at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)
> 2020-06-15T22:06:19.317750+00:00 app[web.1]: at Function.resolve (internal/modules/cjs/helpers.js:78:19)
> 2020-06-15T22:06:19.317751+00:00 app[web.1]: at resolvePath (/app/node_modules/socket.io/lib/index.js:113:20)
> 2020-06-15T22:06:19.317751+00:00 app[web.1]: at Server.serveClient (/app/node_modules/socket.io/lib/index.js:116:25)
> 2020-06-15T22:06:19.317751+00:00 app[web.1]: at new Server (/app/node_modules/socket.io/lib/index.js:53:8)
> 2020-06-15T22:06:19.317752+00:00 app[web.1]: at Server (/app/node_modules/socket.io/lib/index.js:44:41)
> 2020-06-15T22:06:19.317752+00:00 app[web.1]: at Object.<anonymous> (/app/start_server.js:10:12)
> 2020-06-15T22:06:19.317753+00:00 app[web.1]: at Module._compile (internal/modules/cjs/loader.js:1138:30)
> 2020-06-15T22:06:19.317753+00:00 app[web.1]: at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
> 2020-06-15T22:06:19.317753+00:00 app[web.1]: at Module.load (internal/modules/cjs/loader.js:986:32) {
> 2020-06-15T22:06:19.317754+00:00 app[web.1]: code: 'MODULE_NOT_FOUND',
> 2020-06-15T22:06:19.317754+00:00 app[web.1]: requireStack: [
> 2020-06-15T22:06:19.317754+00:00 app[web.1]: '/app/node_modules/socket.io/lib/index.js',
> 2020-06-15T22:06:19.317755+00:00 app[web.1]: '/app/start_server.js'
> 2020-06-15T22:06:19.317755+00:00 app[web.1]: ]
> 2020-06-15T22:06:19.317755+00:00 app[web.1]: }
> ```
> 
> **Code:**
> 
> ```
> const express = require('express');
> const socketIO = require('socket.io');
> 
> const PORT = process.env.PORT || 3000;
> 
> const server = express()
>   .use((req, res) => res.send("Funciona"))
>   .listen(PORT, () => console.log(`Listening on ${PORT}`));
> 
> const io = socketIO(server);
> 
> io.on('connection', (socket) => {
>   console.log('Client connected');
>   socket.on('disconnect', () => console.log('Client disconnected'));
> });
> ```
> 
> how do I fix this error?

Just delete the socket.io-client folder from node-modules

**Comment by mddarmawan** [comment]
@ShintaroBRL, please close this issue if you think it is already solved.
